### PR TITLE
Add STATIC_ROOT to include paths

### PR DESCRIPTION
**Pull request by jimfunk**
Adding STATIC_ROOT to include paths to allow for online compression when DEBUG = False

### CODE REVIEW

**Comment by gasman** [comment]
Hi @jimfunk - I don't think this change is valid. The include path in django-libsass is designed to match the locations used by Django's STATICFILES_FINDERS, so that any path recognised by Django as a valid source location for static files (e.g. by `./manage.py collectstatic` and the dev server) is also valid within SASS files.

STATIC_ROOT is not one of those recognised paths - Django only uses it as the destination for `./manage.py collectstatic`, not as a place to put your own static files. In a correctly-configured project, all of the files found in STATIC_ROOT (except for django-compressor's CACHE folder, which is a special case) will also exist in a location recognised by the staticfiles finders (for example, a 'static' folder in one of your apps) so there should never be any reason for the SASS compiler to look in STATIC_ROOT.

Will close this issue now, but if there's something I've misunderstood and you can provide further clarification, please reopen.

**Comment by jimfunk** [comment]
That's fine if you are using offline compression, but if offline compression is disabled and DEBUG == False, then the staticfiles loaders won't include the application paths.

**Comment by gasman** [comment]
The staticfiles loaders will always include application paths as long as `'django.contrib.staticfiles.finders.AppDirectoriesFinder'` is included in STATICFILES_FINDERS - that doesn't change according to the offline compression / DEBUG settings, surely?

**Comment by jimfunk** [comment]
Apparently it does, at least in Django 1.8

**Comment by gasman** [comment]
Hmm... could you put together a minimal example project that demonstrates this, plese?

**Comment by jimfunk** [comment]
It seems you're right. The app I was working on is installed in an odd way and staticfiles finders wasn't picking up the app paths. Sorry for the noise.

**Comment by gasman** [comment]
No worries. Always good to have the chance to think these things through systematically!

**Pull request closed without merging**
